apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: db-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: DB_NAME
              value: "fitness_tracking"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
