apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-service
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: workout-service
          image: harshapaul265/k8n-workout-service:latest # Use the correct image name here
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service
spec:
  selector:
    app: workout-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
